# Generated by Django 4.1.3 on 2022-11-26 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_remove_todoitem_todo_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='notification_method',
            field=models.CharField(choices=[('em', 'Почта'), ('ph', 'телефон')], max_length=20, verbose_name='Метод оповещения'),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='reminder_type',
            field=models.CharField(choices=[('один раз', 'один раз'), ('с интервалом', 'интервал'), ('каждый день', 'каждый день'), ('по триггеру', 'по триггеру')], default='один раз', max_length=20, verbose_name='Тип напоминания'),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='status',
            field=models.CharField(choices=[('открыта', 'открыта'), ('закрыта', 'закрыта'), ('завершена', 'завершена')], default='открыта', max_length=20, verbose_name='Статус'),
        ),
    ]
