# Generated by Django 4.1.3 on 2022-11-26 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0003_alter_todoitem_notification_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='notification_method',
            field=models.CharField(choices=[('почта', 'Почта'), ('телефонн', 'телефон')], max_length=20, verbose_name='Метод оповещения'),
        ),
    ]
